# Creating Deep Neural Network for classifying famous IRIS dataset

<b>Importing Dataset<b/>

In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

<b>IRIS dataset description<b/>

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X = iris.data

In [7]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y = iris.target

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

<b>One Hot Encoding<b/>

In [10]:
#class1 = [1,0,0], class2 = [0,1,0], class3 = [0,0,1]

In [12]:
from keras.utils import to_categorical

In [13]:
y = to_categorical(y)

In [15]:
y.shape

(150, 3)

<b>Splitting data into training & test set<b/>

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [18]:
X_test.shape

(50, 4)

In [19]:
X_train.shape

(100, 4)

In [20]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

<b>Scaling Data<b/>

In [21]:
from sklearn.preprocessing import MinMaxScaler

In [22]:
scaler = MinMaxScaler()

In [23]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [26]:
scaled_X_train = scaler.transform(X_train)

In [28]:
scaled_X_train

array([[0.41176471, 0.40909091, 0.55357143, 0.5       ],
       [0.97058824, 0.45454545, 0.98214286, 0.83333333],
       [0.38235294, 0.45454545, 0.60714286, 0.58333333],
       [0.23529412, 0.68181818, 0.05357143, 0.04166667],
       [1.        , 0.36363636, 1.        , 0.79166667],
       [0.44117647, 0.31818182, 0.53571429, 0.375     ],
       [0.26470588, 0.63636364, 0.05357143, 0.04166667],
       [0.20588235, 0.68181818, 0.03571429, 0.08333333],
       [0.23529412, 0.81818182, 0.14285714, 0.125     ],
       [0.20588235, 0.        , 0.42857143, 0.375     ],
       [0.58823529, 0.31818182, 0.67857143, 0.70833333],
       [0.14705882, 0.63636364, 0.14285714, 0.04166667],
       [0.20588235, 0.45454545, 0.08928571, 0.04166667],
       [0.23529412, 0.59090909, 0.10714286, 0.16666667],
       [0.38235294, 0.31818182, 0.55357143, 0.5       ],
       [0.23529412, 0.63636364, 0.07142857, 0.04166667],
       [0.41176471, 0.45454545, 0.55357143, 0.45833333],
       [1.        , 0.81818182,

In [29]:
scaled_X_test = scaler.transform(X_test)

In [30]:
scaled_X_test

array([[ 0.52941176,  0.36363636,  0.64285714,  0.45833333],
       [ 0.41176471,  0.81818182,  0.10714286,  0.08333333],
       [ 1.        ,  0.27272727,  1.03571429,  0.91666667],
       [ 0.5       ,  0.40909091,  0.60714286,  0.58333333],
       [ 0.73529412,  0.36363636,  0.66071429,  0.54166667],
       [ 0.32352941,  0.63636364,  0.07142857,  0.125     ],
       [ 0.38235294,  0.40909091,  0.44642857,  0.5       ],
       [ 0.76470588,  0.5       ,  0.71428571,  0.91666667],
       [ 0.55882353,  0.09090909,  0.60714286,  0.58333333],
       [ 0.44117647,  0.31818182,  0.5       ,  0.45833333],
       [ 0.64705882,  0.54545455,  0.71428571,  0.79166667],
       [ 0.14705882,  0.45454545,  0.05357143,  0.        ],
       [ 0.35294118,  0.68181818,  0.03571429,  0.04166667],
       [ 0.17647059,  0.5       ,  0.07142857,  0.        ],
       [ 0.23529412,  0.81818182,  0.07142857,  0.08333333],
       [ 0.58823529,  0.59090909,  0.64285714,  0.625     ],
       [ 0.64705882,  0.

<b>Creating Neural Network for model training<b/>

In [41]:
from keras.models import Sequential
from keras.layers import Dense

In [42]:
model = Sequential()

In [43]:
model.add(Dense(8, input_dim = 4, activation = 'relu'))
model.add(Dense(8, input_dim = 4, activation = 'relu'))
model.add(Dense(3, activation = 'softmax'))

In [44]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer = 'adam')

In [45]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [48]:
model.fit(scaled_X_train, y_train, epochs=150, verbose=2)

Epoch 1/150
4/4 - 0s - loss: 0.4554 - accuracy: 0.9600
Epoch 2/150
4/4 - 0s - loss: 0.4544 - accuracy: 0.9600
Epoch 3/150
4/4 - 0s - loss: 0.4534 - accuracy: 0.9600
Epoch 4/150
4/4 - 0s - loss: 0.4521 - accuracy: 0.9600
Epoch 5/150
4/4 - 0s - loss: 0.4509 - accuracy: 0.9600
Epoch 6/150
4/4 - 0s - loss: 0.4496 - accuracy: 0.9600
Epoch 7/150
4/4 - 0s - loss: 0.4487 - accuracy: 0.9600
Epoch 8/150
4/4 - 0s - loss: 0.4475 - accuracy: 0.9600
Epoch 9/150
4/4 - 0s - loss: 0.4462 - accuracy: 0.9600
Epoch 10/150
4/4 - 0s - loss: 0.4452 - accuracy: 0.9600
Epoch 11/150
4/4 - 0s - loss: 0.4438 - accuracy: 0.9600
Epoch 12/150
4/4 - 0s - loss: 0.4428 - accuracy: 0.9600
Epoch 13/150
4/4 - 0s - loss: 0.4416 - accuracy: 0.9600
Epoch 14/150
4/4 - 0s - loss: 0.4405 - accuracy: 0.9600
Epoch 15/150
4/4 - 0s - loss: 0.4394 - accuracy: 0.9700
Epoch 16/150
4/4 - 0s - loss: 0.4382 - accuracy: 0.9800
Epoch 17/150
4/4 - 0s - loss: 0.4371 - accuracy: 0.9800
Epoch 18/150
4/4 - 0s - loss: 0.4361 - accuracy: 0.9800
E

Epoch 147/150
4/4 - 0s - loss: 0.2946 - accuracy: 0.9700
Epoch 148/150
4/4 - 0s - loss: 0.2932 - accuracy: 0.9800
Epoch 149/150
4/4 - 0s - loss: 0.2922 - accuracy: 0.9800
Epoch 150/150
4/4 - 0s - loss: 0.2905 - accuracy: 0.9800


In [49]:
model.predict(scaled_X_test)

array([[2.12095119e-02, 6.46778941e-01, 3.32011491e-01],
       [9.95713592e-01, 4.00249055e-03, 2.83931149e-04],
       [2.26915930e-03, 1.82958350e-01, 8.14772546e-01],
       [1.80706829e-02, 5.96311569e-01, 3.85617703e-01],
       [1.45684890e-02, 5.90776682e-01, 3.94654870e-01],
       [9.87649143e-01, 1.13963690e-02, 9.54476942e-04],
       [3.06285061e-02, 7.57475972e-01, 2.11895525e-01],
       [4.78699990e-03, 3.03753048e-01, 6.91459954e-01],
       [1.31649021e-02, 4.20214325e-01, 5.66620827e-01],
       [2.83187758e-02, 7.17928290e-01, 2.53752917e-01],
       [8.17040168e-03, 4.17839974e-01, 5.73989630e-01],
       [9.93007302e-01, 6.41449215e-03, 5.78121922e-04],
       [9.96389389e-01, 3.38335824e-03, 2.27196346e-04],
       [9.93571281e-01, 5.90703264e-03, 5.21705661e-04],
       [9.98023152e-01, 1.83002837e-03, 1.46800361e-04],
       [1.60202403e-02, 6.43124461e-01, 3.40855300e-01],
       [4.09900863e-03, 2.32998103e-01, 7.62902915e-01],
       [3.10289226e-02, 6.97367

<b>Prediction & Metrics reporting<b/>

In [50]:
model.predict_classes(scaled_X_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [51]:
predictions = model.predict_classes(scaled_X_test)

In [52]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [53]:
from sklearn.metrics import confusion_matrix, classification_report

In [54]:
print(confusion_matrix(y_test.argmax(axis=1), predictions))
print(classification_report(y_test.argmax(axis=1), predictions))

[[19  0  0]
 [ 0 14  1]
 [ 0  0 16]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.93      0.97        15
           2       0.94      1.00      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



<b>Saving Model<b/>

In [55]:
model.save('IrisNlpDeep.h5')

In [56]:
from keras.models import load_model

In [57]:
new_model = load_model('IrisNLpDeep.h5')

In [58]:
new_model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)